server.port=8083

spring.application.name=detection-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/review_detection_db

# Optional logging
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG